export const VOCABULARY_STORAGE_KEY = "thai-learning-teacher-vocabulary";
export const SENTENCE_STORAGE_KEY = "thai-learning-teacher-sentences";
export const QUIZ_STORAGE_KEY = "thai-learning-teacher-quiz-questions";
export const LEARNING_PROGRESS_STORAGE_KEY = "thai-learning-progress";
export const BOOKING_STORAGE_KEY = "thai-learning-bookings";

export const defaultFlashcards = [
  { id: "demo-vocab-001", category: "問候", zh: "你好", th: "สวัสดี", py: "sà-wàt-dii", image: "", audio: "" },
  { id: "demo-vocab-002", category: "問候", zh: "謝謝", th: "ขอบคุณ", py: "khɔ̀ɔp-khun", image: "", audio: "" },
  { id: "demo-vocab-003", category: "問候", zh: "對不起", th: "ขอโทษ", py: "khɔ̌ɔ-thôot", image: "", audio: "" },
  { id: "demo-vocab-004", category: "問候", zh: "再見", th: "ลาก่อน", py: "laa-gɔ̀ɔn", image: "", audio: "" },
  { id: "demo-vocab-005", category: "問候", zh: "沒關係", th: "ไม่เป็นไร", py: "mâi-bpen-rai", image: "", audio: "" },
  { id: "demo-vocab-006", category: "問候", zh: "是", th: "ใช่", py: "châi", image: "", audio: "" },
  { id: "demo-vocab-007", category: "問候", zh: "不是", th: "ไม่ใช่", py: "mâi-châi", image: "", audio: "" },
  { id: "demo-vocab-008", category: "數字", zh: "一", th: "หนึ่ง", py: "nʉ̀ng", image: "", audio: "" },
  { id: "demo-vocab-009", category: "數字", zh: "二", th: "สอง", py: "sɔ̌ɔng", image: "", audio: "" },
  { id: "demo-vocab-010", category: "數字", zh: "三", th: "สาม", py: "sǎam", image: "", audio: "" },
  { id: "demo-vocab-011", category: "數字", zh: "四", th: "สี่", py: "sìi", image: "", audio: "" },
  { id: "demo-vocab-012", category: "數字", zh: "五", th: "ห้า", py: "hâa", image: "", audio: "" },
  { id: "demo-vocab-013", category: "數字", zh: "十", th: "สิบ", py: "sìp", image: "", audio: "" },
  { id: "demo-vocab-014", category: "數字", zh: "一百", th: "หนึ่งร้อย", py: "nʉ̀ng-rɔ́ɔi", image: "", audio: "" },
  { id: "demo-vocab-015", category: "餐廳", zh: "水", th: "น้ำ", py: "náam", image: "", audio: "" },
  { id: "demo-vocab-016", category: "餐廳", zh: "飯", th: "ข้าว", py: "khâao", image: "", audio: "" },
  { id: "demo-vocab-017", category: "餐廳", zh: "咖啡", th: "กาแฟ", py: "gaa-fɛɛ", image: "", audio: "" },
  { id: "demo-vocab-018", category: "餐廳", zh: "茶", th: "ชา", py: "chaa", image: "", audio: "" },
  { id: "demo-vocab-019", category: "餐廳", zh: "菜單", th: "เมนู", py: "mee-nuu", image: "", audio: "" },
  { id: "demo-vocab-020", category: "餐廳", zh: "好吃", th: "อร่อย", py: "à-rɔ̀i", image: "", audio: "" },
  { id: "demo-vocab-021", category: "交通", zh: "計程車", th: "แท็กซี่", py: "thɛ́k-sîi", image: "", audio: "" },
  { id: "demo-vocab-022", category: "交通", zh: "公車", th: "รถเมล์", py: "rót-mee", image: "", audio: "" },
  { id: "demo-vocab-023", category: "交通", zh: "車站", th: "สถานี", py: "sà-thǎa-nii", image: "", audio: "" },
  { id: "demo-vocab-024", category: "交通", zh: "機場", th: "สนามบิน", py: "sà-nǎam-bin", image: "", audio: "" },
  { id: "demo-vocab-025", category: "交通", zh: "左邊", th: "ซ้าย", py: "sáai", image: "", audio: "" },
  { id: "demo-vocab-026", category: "交通", zh: "右邊", th: "ขวา", py: "khwǎa", image: "", audio: "" },
  { id: "demo-vocab-027", category: "購物", zh: "多少錢", th: "เท่าไหร่", py: "thâo-rài", image: "", audio: "" },
  { id: "demo-vocab-028", category: "購物", zh: "便宜", th: "ถูก", py: "thùuk", image: "", audio: "" },
  { id: "demo-vocab-029", category: "購物", zh: "貴", th: "แพง", py: "phɛɛng", image: "", audio: "" },
  { id: "demo-vocab-030", category: "購物", zh: "買", th: "ซื้อ", py: "sʉ́ʉ", image: "", audio: "" },
  { id: "demo-vocab-031", category: "購物", zh: "賣", th: "ขาย", py: "khǎai", image: "", audio: "" },
  { id: "demo-vocab-032", category: "購物", zh: "折扣", th: "ลดราคา", py: "lót-raa-khaa", image: "", audio: "" },
  { id: "demo-vocab-033", category: "日常生活", zh: "家", th: "บ้าน", py: "bâan", image: "", audio: "" },
  { id: "demo-vocab-034", category: "日常生活", zh: "學校", th: "โรงเรียน", py: "roong-rian", image: "", audio: "" },
  { id: "demo-vocab-035", category: "日常生活", zh: "老師", th: "ครู", py: "khruu", image: "", audio: "" },
  { id: "demo-vocab-036", category: "日常生活", zh: "學生", th: "นักเรียน", py: "nák-rian", image: "", audio: "" },
  { id: "demo-vocab-037", category: "日常生活", zh: "朋友", th: "เพื่อน", py: "phʉ̂an", image: "", audio: "" },
  { id: "demo-vocab-038", category: "日常生活", zh: "今天", th: "วันนี้", py: "wan-níi", image: "", audio: "" },
  { id: "demo-vocab-039", category: "旅遊", zh: "旅館", th: "โรงแรม", py: "roong-rɛɛm", image: "", audio: "" },
  { id: "demo-vocab-040", category: "旅遊", zh: "海邊", th: "ทะเล", py: "thá-lee", image: "", audio: "" },
  { id: "demo-vocab-041", category: "旅遊", zh: "市場", th: "ตลาด", py: "tà-làat", image: "", audio: "" },
  { id: "demo-vocab-042", category: "旅遊", zh: "寺廟", th: "วัด", py: "wát", image: "", audio: "" },
  { id: "demo-vocab-043", category: "旅遊", zh: "地圖", th: "แผนที่", py: "phɛ̌ɛn-thîi", image: "", audio: "" },
  { id: "demo-vocab-044", category: "旅遊", zh: "護照", th: "หนังสือเดินทาง", py: "nǎng-sʉ̌ʉ-dəən-thaang", image: "", audio: "" },
  { id: "demo-vocab-045", category: "緊急狀況", zh: "救命", th: "ช่วยด้วย", py: "chûai-dûai", image: "", audio: "" },
  { id: "demo-vocab-046", category: "緊急狀況", zh: "醫院", th: "โรงพยาบาล", py: "roong-phá-yaa-baan", image: "", audio: "" },
  { id: "demo-vocab-047", category: "緊急狀況", zh: "警察", th: "ตำรวจ", py: "tam-rùat", image: "", audio: "" },
  { id: "demo-vocab-048", category: "緊急狀況", zh: "藥局", th: "ร้านขายยา", py: "ráan-khǎai-yaa", image: "", audio: "" },
  { id: "demo-vocab-049", category: "緊急狀況", zh: "不舒服", th: "ไม่สบาย", py: "mâi-sà-baai", image: "", audio: "" },
  { id: "demo-vocab-050", category: "緊急狀況", zh: "迷路", th: "หลงทาง", py: "lǒng-thaang", image: "", audio: "" },
];

export const defaultSentences = [
  {
    id: "demo-sentence-001",
    category: "問候",
    zh: "你好，很高興認識你。",
    th: "สวัสดี ยินดีที่ได้รู้จัก",
    py: "sà-wàt-dii yin-dii thîi dâai rúu-jàk",
    note: "第一次見面時使用",
  },
  {
    id: "demo-sentence-002",
    category: "問候",
    zh: "謝謝你的幫忙。",
    th: "ขอบคุณสำหรับความช่วยเหลือ",
    py: "khɔ̀ɔp-khun sǎm-ràp khwaam chûai-lʉ̌a",
    note: "表達感謝",
  },
  {
    id: "demo-sentence-003",
    category: "問候",
    zh: "不好意思，請再說一次。",
    th: "ขอโทษ กรุณาพูดอีกครั้ง",
    py: "khɔ̌ɔ-thôot gà-rú-naa phûut ìik khráng",
    note: "沒聽清楚時使用",
  },
  {
    id: "demo-sentence-004",
    category: "數字",
    zh: "我要買兩個。",
    th: "ฉันต้องการซื้อสองอัน",
    py: "chǎn tɔ̂ng-gaan sʉ́ʉ sɔ̌ɔng an",
    note: "購物數量句型",
  },
  {
    id: "demo-sentence-005",
    category: "數字",
    zh: "這個一百泰銖。",
    th: "อันนี้หนึ่งร้อยบาท",
    py: "an-níi nʉ̀ng-rɔ́ɔi bàat",
    note: "價格表達",
  },
  {
    id: "demo-sentence-006",
    category: "數字",
    zh: "我們有三個人。",
    th: "พวกเรามีสามคน",
    py: "phûak-rao mii sǎam khon",
    note: "人數表達",
  },
  {
    id: "demo-sentence-007",
    category: "餐廳",
    zh: "我想喝水。",
    th: "ฉันอยากดื่มน้ำ",
    py: "chǎn yàak dʉ̀ʉm náam",
    note: "我想要……",
  },
  {
    id: "demo-sentence-008",
    category: "餐廳",
    zh: "請給我菜單。",
    th: "ขอเมนูหน่อย",
    py: "khɔ̌ɔ mee-nuu nɔ̀i",
    note: "餐廳點餐",
  },
  {
    id: "demo-sentence-009",
    category: "餐廳",
    zh: "這個很好吃。",
    th: "อันนี้อร่อยมาก",
    py: "an-níi à-rɔ̀i mâak",
    note: "稱讚食物",
  },
  {
    id: "demo-sentence-010",
    category: "餐廳",
    zh: "不要辣。",
    th: "ไม่เอาเผ็ด",
    py: "mâi ao phèt",
    note: "調整口味",
  },
  {
    id: "demo-sentence-011",
    category: "交通",
    zh: "我要去機場。",
    th: "ฉันจะไปสนามบิน",
    py: "chǎn jà bpai sà-nǎam-bin",
    note: "搭車目的地",
  },
  {
    id: "demo-sentence-012",
    category: "交通",
    zh: "車站在哪裡？",
    th: "สถานีอยู่ที่ไหน",
    py: "sà-thǎa-nii yùu thîi nǎi",
    note: "問地點",
  },
  {
    id: "demo-sentence-013",
    category: "交通",
    zh: "請在左邊停車。",
    th: "กรุณาจอดทางซ้าย",
    py: "gà-rú-naa jɔ̀ɔt thaang sáai",
    note: "告訴司機方向",
  },
  {
    id: "demo-sentence-014",
    category: "交通",
    zh: "到這裡要多久？",
    th: "ไปที่นี่ใช้เวลานานไหม",
    py: "bpai thîi-nîi chái wee-laa naan mǎi",
    note: "詢問時間",
  },
  {
    id: "demo-sentence-015",
    category: "購物",
    zh: "這個多少錢？",
    th: "อันนี้ราคาเท่าไหร่",
    py: "an-níi raa-khaa thâo-rài",
    note: "購物常用",
  },
  {
    id: "demo-sentence-016",
    category: "購物",
    zh: "可以便宜一點嗎？",
    th: "ลดราคาหน่อยได้ไหม",
    py: "lót raa-khaa nɔ̀i dâai mǎi",
    note: "議價句型",
  },
  {
    id: "demo-sentence-017",
    category: "購物",
    zh: "我要買這個。",
    th: "ฉันจะซื้ออันนี้",
    py: "chǎn jà sʉ́ʉ an-níi",
    note: "決定購買",
  },
  {
    id: "demo-sentence-018",
    category: "購物",
    zh: "有折扣嗎？",
    th: "มีส่วนลดไหม",
    py: "mii sùan-lót mǎi",
    note: "詢問優惠",
  },
  {
    id: "demo-sentence-019",
    category: "日常生活",
    zh: "我今天要去學校。",
    th: "วันนี้ฉันจะไปโรงเรียน",
    py: "wan-níi chǎn jà bpai roong-rian",
    note: "日常行程",
  },
  {
    id: "demo-sentence-020",
    category: "日常生活",
    zh: "老師在教室裡。",
    th: "ครูอยู่ในห้องเรียน",
    py: "khruu yùu nai hɔ̂ng-rian",
    note: "位置句型",
  },
  {
    id: "demo-sentence-021",
    category: "日常生活",
    zh: "我和朋友一起吃飯。",
    th: "ฉันกินข้าวกับเพื่อน",
    py: "chǎn gin khâao gàp phʉ̂an",
    note: "和……一起",
  },
  {
    id: "demo-sentence-022",
    category: "日常生活",
    zh: "我今天不舒服。",
    th: "วันนี้ฉันไม่สบาย",
    py: "wan-níi chǎn mâi sà-baai",
    note: "身體狀況",
  },
  {
    id: "demo-sentence-023",
    category: "旅遊",
    zh: "我住在這間旅館。",
    th: "ฉันพักที่โรงแรมนี้",
    py: "chǎn phák thîi roong-rɛɛm níi",
    note: "住宿句型",
  },
  {
    id: "demo-sentence-024",
    category: "旅遊",
    zh: "請給我一張地圖。",
    th: "ขอแผนที่หนึ่งใบ",
    py: "khɔ̌ɔ phɛ̌ɛn-thîi nʉ̀ng bai",
    note: "旅遊求助",
  },
  {
    id: "demo-sentence-025",
    category: "旅遊",
    zh: "這個市場很有名。",
    th: "ตลาดนี้มีชื่อเสียงมาก",
    py: "tà-làat níi mii chʉ̂ʉ-sǐang mâak",
    note: "描述景點",
  },
  {
    id: "demo-sentence-026",
    category: "旅遊",
    zh: "我想去海邊。",
    th: "ฉันอยากไปทะเล",
    py: "chǎn yàak bpai thá-lee",
    note: "想去……",
  },
  {
    id: "demo-sentence-027",
    category: "緊急狀況",
    zh: "救命！我迷路了。",
    th: "ช่วยด้วย ฉันหลงทาง",
    py: "chûai-dûai chǎn lǒng-thaang",
    note: "緊急求助",
  },
  {
    id: "demo-sentence-028",
    category: "緊急狀況",
    zh: "請帶我去醫院。",
    th: "กรุณาพาฉันไปโรงพยาบาล",
    py: "gà-rú-naa phaa chǎn bpai roong-phá-yaa-baan",
    note: "醫療求助",
  },
  {
    id: "demo-sentence-029",
    category: "緊急狀況",
    zh: "我要找警察。",
    th: "ฉันต้องการหาตำรวจ",
    py: "chǎn tɔ̂ng-gaan hǎa tam-rùat",
    note: "尋求協助",
  },
  {
    id: "demo-sentence-030",
    category: "緊急狀況",
    zh: "附近有藥局嗎？",
    th: "แถวนี้มีร้านขายยาไหม",
    py: "thɛ̌eo-níi mii ráan-khǎai-yaa mǎi",
    note: "詢問藥局",
  },
];

export const defaultQuizQuestions = [
  {
    id: "demo-quiz-001",
    category: "問候",
    question: "泰文的「你好」怎麼說？",
    optionA: "สวัสดี",
    optionB: "ขอบคุณ",
    optionC: "ลาก่อน",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-002",
    category: "問候",
    question: "泰文的「謝謝」怎麼說？",
    optionA: "ขอโทษ",
    optionB: "ขอบคุณ",
    optionC: "ไม่ใช่",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-003",
    category: "問候",
    question: "「ไม่เป็นไร」的中文意思是？",
    optionA: "沒關係",
    optionB: "再見",
    optionC: "對不起",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-004",
    category: "數字",
    question: "泰文的「一」是哪一個？",
    optionA: "สอง",
    optionB: "สาม",
    optionC: "หนึ่ง",
    correctAnswer: "C",
  },
  {
    id: "demo-quiz-005",
    category: "數字",
    question: "「ห้า」代表哪個數字？",
    optionA: "三",
    optionB: "五",
    optionC: "十",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-006",
    category: "數字",
    question: "泰文的「十」怎麼說？",
    optionA: "สิบ",
    optionB: "สี่",
    optionC: "หนึ่งร้อย",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-007",
    category: "餐廳",
    question: "泰文的「水」是哪一個？",
    optionA: "ข้าว",
    optionB: "น้ำ",
    optionC: "ชา",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-008",
    category: "餐廳",
    question: "「กาแฟ」是什麼？",
    optionA: "咖啡",
    optionB: "茶",
    optionC: "菜單",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-009",
    category: "餐廳",
    question: "泰文的「好吃」怎麼說？",
    optionA: "แพง",
    optionB: "ถูก",
    optionC: "อร่อย",
    correctAnswer: "C",
  },
  {
    id: "demo-quiz-010",
    category: "餐廳",
    question: "「ขอเมนูหน่อย」適合在什麼情境使用？",
    optionA: "搭車",
    optionB: "餐廳點餐",
    optionC: "看醫生",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-011",
    category: "交通",
    question: "泰文的「計程車」是哪一個？",
    optionA: "แท็กซี่",
    optionB: "รถเมล์",
    optionC: "สถานี",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-012",
    category: "交通",
    question: "「สนามบิน」的中文意思是？",
    optionA: "車站",
    optionB: "機場",
    optionC: "市場",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-013",
    category: "交通",
    question: "泰文的「左邊」怎麼說？",
    optionA: "ขวา",
    optionB: "ซ้าย",
    optionC: "ตรง",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-014",
    category: "交通",
    question: "「กรุณาจอดทางซ้าย」是什麼意思？",
    optionA: "請在左邊停車",
    optionB: "請去機場",
    optionC: "請等一下",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-015",
    category: "購物",
    question: "泰文的「多少錢」是哪一個？",
    optionA: "ลดราคา",
    optionB: "เท่าไหร่",
    optionC: "ซื้อ",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-016",
    category: "購物",
    question: "「แพง」的中文意思是？",
    optionA: "便宜",
    optionB: "折扣",
    optionC: "貴",
    correctAnswer: "C",
  },
  {
    id: "demo-quiz-017",
    category: "購物",
    question: "泰文的「買」怎麼說？",
    optionA: "ซื้อ",
    optionB: "ขาย",
    optionC: "ถูก",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-018",
    category: "購物",
    question: "「มีส่วนลดไหม」是在問什麼？",
    optionA: "可以刷卡嗎",
    optionB: "有折扣嗎",
    optionC: "在哪裡",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-019",
    category: "日常生活",
    question: "泰文的「老師」是哪一個？",
    optionA: "นักเรียน",
    optionB: "เพื่อน",
    optionC: "ครู",
    correctAnswer: "C",
  },
  {
    id: "demo-quiz-020",
    category: "日常生活",
    question: "「บ้าน」的中文意思是？",
    optionA: "家",
    optionB: "學校",
    optionC: "今天",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-021",
    category: "日常生活",
    question: "泰文的「朋友」怎麼說？",
    optionA: "วันนี้",
    optionB: "เพื่อน",
    optionC: "โรงเรียน",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-022",
    category: "日常生活",
    question: "「วันนี้」代表什麼？",
    optionA: "明天",
    optionB: "昨天",
    optionC: "今天",
    correctAnswer: "C",
  },
  {
    id: "demo-quiz-023",
    category: "旅遊",
    question: "泰文的「旅館」是哪一個？",
    optionA: "ตลาด",
    optionB: "โรงแรม",
    optionC: "วัด",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-024",
    category: "旅遊",
    question: "「ทะเล」的中文意思是？",
    optionA: "海邊",
    optionB: "地圖",
    optionC: "寺廟",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-025",
    category: "旅遊",
    question: "泰文的「護照」怎麼說？",
    optionA: "แผนที่",
    optionB: "หนังสือเดินทาง",
    optionC: "สนามบิน",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-026",
    category: "旅遊",
    question: "「ตลาด」是什麼地方？",
    optionA: "市場",
    optionB: "旅館",
    optionC: "醫院",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-027",
    category: "緊急狀況",
    question: "泰文的「救命」是哪一個？",
    optionA: "ไม่สบาย",
    optionB: "หลงทาง",
    optionC: "ช่วยด้วย",
    correctAnswer: "C",
  },
  {
    id: "demo-quiz-028",
    category: "緊急狀況",
    question: "「โรงพยาบาล」的中文意思是？",
    optionA: "醫院",
    optionB: "警察",
    optionC: "藥局",
    correctAnswer: "A",
  },
  {
    id: "demo-quiz-029",
    category: "緊急狀況",
    question: "泰文的「警察」怎麼說？",
    optionA: "ร้านขายยา",
    optionB: "ตำรวจ",
    optionC: "โรงแรม",
    correctAnswer: "B",
  },
  {
    id: "demo-quiz-030",
    category: "緊急狀況",
    question: "「ฉันหลงทาง」是什麼意思？",
    optionA: "我不舒服",
    optionB: "我想喝水",
    optionC: "我迷路了",
    correctAnswer: "C",
  },
];
